config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: %i[new create]
    resources :movies, only: %i[show]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true

  has_one_attached :image_url
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def destroy
  #   @bookmark.destroy
  #   redirect_to list_path(@bookmark.list)
  # end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def show
  end


  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<h1>New Bookmark</h1>

<%= simple_form_for [list, bookmark] do |form| %>
  <%= form.association :movie %>
  <%= form.association :list %>
  <%= form.input :comment %>

  <%= form.button :submit, "Create Bookmark" %>
<% end %>

<%= link_to "Back to List", list_path(@list) %>

app/views/bookmarks/index.html.erb
<h1>All Bookmarks</h1>

<% @bookmarks.each do |bookmark| %>
  <div>
    <%= bookmark.movie.title %>
    <%= link_to bookmark.comment, bookmark_path(bookmark) %>
  </div>
<% end %>

<%= link_to "New Bookmark", new_bookmark_path %>

app/views/bookmarks/new.html.erb
<%= render "form", bookmark: @bookmark, list: @list%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa-solid fa-clapperboard"></i>
        My Movie Lists
      </a>

      <div class="ml-auto">
        <a href="<%= new_list_path %>" class="btn btn-primary">Add a New List</a>
        <a href="<%= lists_path %>" class="btn btn-secondary">All My Lists</a>
      </div>
    </div>
  </nav>


    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url, as: :file %>
  <%= f.submit "Create List" %>
<% end %>

app/views/lists/index.html.erb
<div class="jumbotron jumbotron-fluid bg-dark text-white">
  <div class="container">
    <%= image_tag "theatre.png", class: "img-fluid", alt: "Theatre Cover", style: "max-height: 300px; width: 100%;" %>
  </div>
</div>

<div class="container mt-4">
  <h1>All Lists</h1>

  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <% if list.image_url.attached?%>
            <%= cl_image_tag list.image_url.key, height: 300, width: 400, crop: :fill%>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <p class="card-text">Number of movies: <%= list.movies.count %></p>
            <%= link_to "View List", list_path(list), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<h5>Movies</h5>


<div class="container">
  <div class="row">
    <% @list.movies.each do |movie| %>
      <div class="col-md-4 mb-4">
        <div class="card">
          <%= image_tag movie.poster_url, class: "card-img-top", alt: movie.title %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text">Rating: <%= movie.rating %>/10</p>
            <strong>Comments:</strong>
            <ul>
              <% movie.bookmarks.each do |bookmark| %>
                <li><%= bookmark.comment %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "New Bookmark", new_list_bookmark_path(@list) %>